DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE (
   ID 				INT 	PRIMARY KEY     NOT NULL,
   REFERENCE        INT                     NOT NULL,
   LASTNAME        	VARCHAR    				NOT NULL,
   FIRSTNAME        VARCHAR    				NOT NULL,
   DATEOFBIRTH     	DATE,
   ADDRESS_NUMBER	VARCHAR,
   ADDRESS_STREET     	VARCHAR,
   ADDRESS_POSTALCODE     	VARCHAR,
   ADDRESS_COUNTRY     	VARCHAR,
   JOINED_COMPANY_DATE date,
   GROSS_MONTHLY_SALARY         	real,
   IS_GRANTED_CAR boolean,
   NB_DAYS_YEARLY_HOLIDAYS int
);